### PR TITLE
[WIP]custom namespace /POST for things route

### PR DESCRIPTION
**Pull request by Pranshu-G**
Signed-off-by: Pranshu-G <pranshu.grover18@gmail.com>

Fixes: #550 add custom namespace route.
Missing test case and documentation.

### CODE REVIEW

**Comment by Pranshu-G** [comment]
For the `ThingIdTest`, should I go about it by performing a POST request to the `/things/namespace=my.cool.namespace` with response as ThingId with `namespace = my.cool.namespace` ?

**Review by Pranshu-G — COMMENTED** [review]
I added a reference to `namespace` parameter to `ditto-api-2.yml` but I am not sure it is reflecting the desired behavior

**Comment by Pranshu-G** [comment]
> Hi @Pranshu-G Thanks for the adjustments - I had another look and added a "review commit". Could you check if that is ok for you? I just applied some formatting and fixed the OpenAPI docs by adding the "Namespace" parameter separately.

Hi @thjaeckle , the changes look fine. The OpenAPI change was necessary since I wasn't able to get the desired output there. Is the PR good to go now?

**Comment by thjaeckle** [comment]
> Is the PR good to go now?

Yes, once the build is "green" we can accept and merge it 👍

**Pull request merged**
