### PR TITLE
Guidance and template to run Ditto with Azure Cosmos DB's API for MongoDB

### PR DESCRIPTION
**Pull request by kaizimmerm**
Hi,

I extended the Azure deployment guide for a CosmosDB variant including an Azure Resource Manager template that provisions the CosmosDb account, the databases as well as the collections.

Note: this is done by template in order to provision [Request Units (RU)](https://docs.microsoft.com/en-us/azure/cosmos-db/request-units).

Kai

### CODE REVIEW

**Comment by yufei-cai** [comment]
Build is failing due to assertions racing with the tested code and winning on the very slow travis machines. I'm working on it.

**Comment by yufei-cai** [comment]
@kaizimmerm Tests are fixed on [bsinno:feature/status-user](https://github.com/bsinno/ditto/tree/feature/status-user). Code review will take a bit of time. Feel free to merge it here given sufficient courage :)

**Comment by ghandim** [comment]
Will give it a try today

**Comment by ghandim** [comment]
@kaizimmerm Get this error "The value of parameter orchestratorProfile.OrchestratorVersion is invalid. Please see https://aka.ms/aks-naming-rules for more details." while executing "az group deployment create..." Any hints?

**Comment by kaizimmerm** [comment]
@ghandim Yeah, sry about that. Forgot to warn you. Kind of "die Katze beißt sich in den Schwanz" problem 😄

**Comment by ghandim** [comment]
BTW: What's the problem of the CosmosDB with our search implementation?

**Comment by kaizimmerm** [comment]
Several differences between the two databases in search behaviour, i.e. many of the Ditto regular expressions will return different results or non at all. So to work on Cosmos many of them have to be adapted.

**Comment by kaizimmerm** [comment]
I merged with master but after that era check failed (I guess my merge commit was not signed off). So I had to force push. I apologise but the content is identical to the original commits.

**Pull request merged**
