### PR TITLE
Relax timing requirement in MongoEventSourceITAssertions.

### PR DESCRIPTION
**Pull request by yufei-cai**
Relax timing requirement so that the MongoDB integration tests fail less often on slow systems.

### CODE REVIEW

**Comment by yufei-cai** [comment]
@thjaeckle License header year checking is not working.

```
Run jitterbit/get-changed-files@v1
Base commit: cf1a678e6ee47f746932055b6fbb460e83ce0c98
Head commit: cba015eb36ca68d0c19d71d93f6e69bfbff1e7bb
Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo.
All: services/utils/persistence/src/test/java/org/eclipse/ditto/services/utils/persistence/mongo/ops/eventsource/MongoEventSourceITAssertions.java
Added: 
Modified: services/utils/persistence/src/test/java/org/eclipse/ditto/services/utils/persistence/mongo/ops/eventsource/MongoEventSourceITAssertions.java
Removed: 
Renamed: 
Added or modified: services/utils/persistence/src/test/java/org/eclipse/ditto/services/utils/persistence/mongo/ops/eventsource/MongoEventSourceITAssertions.java
```

**Comment by thjaeckle** [comment]
@yufei-cai oh, bad .. then just remove the action for now on this branch and merge it - I'll have a look once I'm back.
The issue seems to be known: https://github.com/jitterbit/get-changed-files/issues/7

**Comment by yufei-cai** [comment]
@thjaeckle Does Github actions require special permissions? I get 404 when I try to view or edit the action yaml.

**Comment by thjaeckle** [comment]
@yufei-cai it's just a file in the .github folder top level. Maybe your branch has not yet merged the commit in which I added the file?

**Review by jokraehe — APPROVED** [review]

**Pull request merged**
