### PR TITLE
Fix websocket jwt refresh

### PR DESCRIPTION
**Pull request by jokraehe**
The refresh via protocol message is broken for websocket connections which doesn't subscribe for events as the initial connect always uses an empty authorization context.

### CODE REVIEW

**Comment by thjaeckle** [comment]
Please also cherry-pick the commits to the `release-1.5` branch.

**Review by yufei-cai — COMMENTED** [review]
Added unit tests. Fixed authorization extraction and actor crash on huge expiration.

**Review by yufei-cai — APPROVED** [review]

**Comment by thjaeckle** [comment]
@yufei-cai did you merge the master branch into the release-1.5 branch?
That is wrong as on master there was already a PR containing new apis with "since 2.0.0"

**Comment by yufei-cai** [comment]
@thjaeckle ah, I see. I will reset release-1.5.

**Comment by yufei-cai** [comment]
@thjaeckle I cherry-picked non-merge commits listed in 1.5.1 milestone onto the branch release-1.5.

https://github.com/eclipse/ditto/milestone/30?closed=1

**Comment by thjaeckle** [comment]
@yufei-cai perfect, thanks 👍

**Pull request merged**
