### PR TITLE
Explorer UI: URL parameters for environments

### PR DESCRIPTION
**Pull request by thfries**
Hi ditto team,

please find this PR that addresses issue: #1449 

I allows to
* load environments via `environmentsURL` parameter
* select an environment via `primaryEnvironmentName`

Additional improvements:
* Stacking for (multiple) error toasts (because invalid URL parameters can cause additional errors that were not visible)
* Avoid errors to be thrown twice in ditto rest call
* Optimized layout for long thingIds in tables. Multi-line cells are avoided in general by ellipsis and tooltip. Hidden experimental: you can set `shortenUUID` to true and define a `defaultNamespace` in the environment to get better readable thingIds
* fixed some eslint issues in things.js
* Small fix to de-select favorite filter in case of pinned things

Looking forward to your feedback, Thomas

### CODE REVIEW

**Comment by thjaeckle** [comment]
@thfries again, thanks for the great contribution 👍 
I tried the feature out a little and what I immediately thought:
* it would be great that if you select an environment with the dropdown at the top right to set the query paramter `primaryEnvironmentName=<selected-env>` - that way refreshing the page directly has the correct environment again - and the page incl. selected environment is bookmark-able

Did you already try out the `environmentsURL` feature with a custom hosted environment JSON?

I think once this PR is merged we should really tackle #1496 and add some documentation for the Ditto-UI (especially the "environments" feature) there as well..

**Comment by thfries** [comment]
Hi @thjaeckle,

smart idea, thank you! I added a commit for that 👍

yes, I tested with some sample environments here: https://gist.githubusercontent.com/thfries/5e722197bd74be80fc1c02473753a1e6/raw/4ec788886090daa6c62d90dd5d75e725d80935ab/environments.json. I am going to test next week with some real environments.

Thomas

**Review by thjaeckle — APPROVED** [review]
Hi @thfries 
The feature looks great - thanks for adding the suggested parameter change on environment switch, works 👍 

FMPOV I would approve the PR - please let me know when it would be ready to merge from your side :)

**Comment by thfries** [comment]
OK from my side, too. Removing draft status. Thanks 👍

**Pull request merged**
