### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by yufei-cai**
MongoClientWrapper
- Fixed a leak of event loops if MongoClientWrapper is instantiated more than once
- Configure read preference in users of MongoClientWrapper instead of in its constructor

DefaultStreamSupervisor
- Minimum stream delay is now configurable for DefaultStreamSupervisor
- Removed blocking wait from StreamMetadataPersistence
- Removed a rare scenario where sync timestamp never catches up

ThingPersistenceActor
- Prevented an OutOfMemoryError when DefaultStreamSupervisor start streams too fast
- Fixed message loss due to actor restart

AclEnforcer
- Stop interpreting absence of rights as revocation: This was inconsistent with things-search

Status route
- Removed dynamic adjustment to expected cluster roles: They should never change in a deployment
- Always report "missing-roles" and "extra-roles"

Development Environment
- Make it harder for services to shut themselves down during debug sessions

### CODE REVIEW

**Comment by thjaeckle** [comment]
@yufei-cai is this still a WIP?

**Comment by yufei-cai** [comment]
Working on it. Should finish soon-ish.

**Comment by thjaeckle** [comment]
The test `ThingNamespaceOpsActorIT>EventSourceNamespaceOpsActorTestCases.purgeNamespaceWithSuffixBuilder:64->EventSourceNamespaceOpsActorTestCases.purgeNamespace:121` is failing causing the build error.

**Comment by yufei-cai** [comment]
Travis build succeeded after restart. I suspect Travis hit a performance nadir.

**Pull request merged**
