### PR TITLE
Support for building arm64 ditto snapshot images

### PR DESCRIPTION
**Pull request by ghandim**
Dockerfile for support of building arm64 based ditto snapshot images.
Signed-off-by: Michael Gantert <michael.gantert@bosch.io>

### CODE REVIEW

**Comment by thjaeckle** [comment]
Awesome @ghandim 
Do we maybe already want to add a "release" dockerfile as well and also publish releases to Docker Hub?
Any suggestions for Docker tagnames for such released images?

Then we should also advertise this somewhere in the "installation" or "operation" documentation, that there is the option to run on ARM64.

**Comment by thjaeckle** [comment]
Apparently the "right" way to do this is to use docker "buildx":
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

Example: https://hub.docker.com/r/ckulka/multi-arch-example

**Comment by ghandim** [comment]
@thjaeckle I thought also to that this could be the next steps. OpenJ9 prefixes their image tags with the architecture, e.g. "aarch64-centos-jdk-11.0.10_9_openj9-0.24.0". e.g. Don't know if we need/have a special build environment for arm based builds. Otherwise we have to go for multi architecture build like described here https://admantium.medium.com/docker-building-images-for-multiple-architectures-4f142f6dda71.

**Review by thjaeckle — APPROVED** [review]
LGTM as first step (building snapshot image locally)

Further steps towards multi-arch images have to be discussed.

**Comment by ghandim** [comment]
@thjaeckle Could also be discussed in the context of the packages project, or?

**Comment by thjaeckle** [comment]
@ghandim I don't see it there .. as producing the Docker images is responsibility of the projects, not of the packages project

**Pull request merged**
