### PR TITLE
Restructure Maven Modules

### PR DESCRIPTION
**Pull request by Yannic92**
This PR provides part 13 of #978 

For details please check the ditto 2.0 release notes

### CODE REVIEW

**Review by stmaute — COMMENTED** [review]
Maybe we should document since when these modules are marked as public API?

**Comment by Yannic92** [comment]
> Maybe we should document since when these modules are marked as public API?

I thought about it, but I think git is a better tool to solve this. To find out at what time which set of modules are public API I'd suggest to look at this file for the respective version tag.
Otherwise we would have to keep all versions tracked in DADR-0005.
I don't like this. What do you think?

**Comment by stmaute** [comment]
> > Maybe we should document since when these modules are marked as public API?
> 
> I thought about it, but I think git is a better tool to solve this. To find out at what time which set of modules are public API I'd suggest to look at this file for the respective version tag.
> Otherwise we would have to keep all versions tracked in DADR-0005.
> I don't like this. What do you think?

I also thought about your approach to let git handle this. But I would propose to add something like "Updated API Models for Ditto 2.0 on 04.05.2021" in the first line of DADR-0005. I do not think that we will update the Ditto API this often. And I think it makes sense to have a bit of history in architectural decisions.

**Comment by thjaeckle** [comment]
I agree that we should at least provide a "changelog" to DADRs.
One can look in the Git history after finding out that the DADR was changed with Ditto 2.0

**Comment by thjaeckle** [comment]
@stmaute @Yannic92 I enhanced the already existing changelog on top of the DADR with the change

**Review by thjaeckle — APPROVED** [review]
LGTM 👍 
Awesome refactoring @Yannic92 🎉

**Pull request merged**
